export const appSliderData = [
    {
      image:
        'resources/Dron1.jpg'
    },
    {
      image:
        'resources/Dron2.jpg'
    },
    {
      image:
      'resources/Dron3.jpg'
    },
    {
      image:
      'resources/Dron2.jpg'
    },
    {
      image:
      'resources/Dron2.jpg'
    }
  ];